### ISSUE TITLE
Gerald not work

### ISSUE THREAD

**Issue by CommanderKeef** [GRUFFMAN/Cat-tastrophe_Game#5]
**Describe the bug**
Old mate Gerald is not performing his duties of walking and chasing.

**To Reproduce**
1. Go to Gerald room
2. Approach him

**Expected behavior**
Gerald should chase the player/roam around the room.

**Screenshots**

**Desktop (please complete the following information):**
- Windows 7
- Ultimate SP1

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by GRUFFMAN** [comment]
Gerald is working, He only wasn't before because the player was not tagged and layered as player. He should be working as normal since yesterday. 
I will make improvements to how he works on the weekend and probably change how his sight works or at least make his sight range wider. I will also try to work in some more complex behaviour and get him to notice if you meow.

**Comment by CommanderKeef** [comment]
Thank you brother <3
